name: pinext
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+20

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  antdesign_icons: ^0.0.3
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  cloud_firestore: ^5.6.6
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  elegant_notification: ^2.4.4
  equatable: ^2.0.7
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_core_platform_interface: ^5.4.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_intro: ^3.4.0
  flutter_local_notifications: ^19.0.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0
  intl: ^0.19.0
  lottie: ^3.1.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pie_chart: ^5.4.0
  pretty_dio_logger: ^1.4.0
  quick_actions: ^1.1.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_barcodes: ^29.1.35
  syncfusion_flutter_xlsio: ^29.1.35
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  uuid: ^4.5.1
  very_good_analysis: ^7.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app_icon/
    - assets/privicy_policy/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro.ttf
    - family: Cursive
      fonts:
        - asset: assets/fonts/SeaweedScript-Regular.ttf
    - family: CardTitle
      fonts:
        - asset: assets/fonts/TiltPrism-Regular-VariableFont_XROT,YROT.ttf
    - family: BakbakOne
      fonts:
        - asset: assets/fonts/BakbakOne-Regular.ttf
