name: pinext
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+17

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animate_do: ^3.1.2
  antdesign_icons: ^0.0.3
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  dio: ^5.4.0
  elegant_notification: ^1.11.2
  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_core_platform_interface: 5.0.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_intro: ^3.0.4
  flutter_local_notifications: ^16.3.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  intl: ^0.18.0
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  pie_chart: ^5.4.0
  pretty_dio_logger: ^1.3.1
  quick_actions: ^1.0.6
  shared_preferences: ^2.2.2
  syncfusion_flutter_barcodes: ^24.1.44
  syncfusion_flutter_xlsio: 24.1.44
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  uuid: ^4.1.0
  very_good_analysis: ^5.1.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app_icon/
    - assets/privicy_policy/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro.ttf
    - family: Cursive
      fonts:
        - asset: assets/fonts/SeaweedScript-Regular.ttf
    - family: CardTitle
      fonts:
        - asset: assets/fonts/TiltPrism-Regular-VariableFont_XROT,YROT.ttf
    - family: BakbakOne
      fonts:
        - asset: assets/fonts/BakbakOne-Regular.ttf
