name: pinext
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+16

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  antdesign_icons: ^0.0.3
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  cloud_firestore: ^4.8.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  dio: ^5.2.0+1
  elegant_notification: ^1.10.0
  equatable: ^2.0.5
  firebase_analytics: ^10.4.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_core_platform_interface: 4.8.0
  firebase_crashlytics: ^3.3.2
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_intro: ^3.0.2
  flutter_local_notifications: ^14.1.1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.4
  intl: 0.18.0
  lottie: ^2.4.0
  open_file: ^3.3.1
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  pie_chart: ^5.3.2
  pretty_dio_logger: ^1.3.1
  quick_actions: ^1.0.5
  shared_preferences: ^2.1.2
  syncfusion_flutter_barcodes: ^21.2.9
  syncfusion_flutter_xlsio: 21.2.9
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  very_good_analysis: ^5.0.0+1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app_icon/
    - assets/privicy_policy/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro.ttf
    - family: Cursive
      fonts:
        - asset: assets/fonts/SeaweedScript-Regular.ttf
    - family: CardTitle
      fonts:
        - asset: assets/fonts/TiltPrism-Regular-VariableFont_XROT,YROT.ttf
    - family: BakbakOne
      fonts:
        - asset: assets/fonts/BakbakOne-Regular.ttf
