name: pinext
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+17

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animate_do: ^3.3.3
  antdesign_icons: ^0.0.3
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.3
  cloud_firestore: ^4.15.5
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  dio: ^5.4.1
  elegant_notification: ^1.13.0
  equatable: ^2.0.5
  firebase_analytics: ^10.8.6
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_core_platform_interface: 5.0.0
  firebase_crashlytics: ^3.4.15
  firebase_messaging: ^14.7.16
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_intro: ^3.1.2
  flutter_local_notifications: ^16.3.2
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  intl: ^0.18.0
  lottie: ^3.1.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  pie_chart: ^5.4.0
  pretty_dio_logger: ^1.3.1
  quick_actions: ^1.0.7
  shared_preferences: ^2.2.2
  syncfusion_flutter_barcodes: ^24.2.7
  syncfusion_flutter_xlsio: 24.2.7
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  very_good_analysis: ^5.1.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app_icon/
    - assets/privicy_policy/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro.ttf
    - family: Cursive
      fonts:
        - asset: assets/fonts/SeaweedScript-Regular.ttf
    - family: CardTitle
      fonts:
        - asset: assets/fonts/TiltPrism-Regular-VariableFont_XROT,YROT.ttf
    - family: BakbakOne
      fonts:
        - asset: assets/fonts/BakbakOne-Regular.ttf
